simplify JIRA request code

diff --git a/bin/flow-jira b/bin/flow-jira
--- a/bin/flow-jira
+++ b/bin/flow-jira
@@ -11,26 +11,4 @@ selector=${2:-'.'}
 
 result=$(fetch $url_path)
 
-
-ruby_code=$(<<-EOF
-# JIRA responses include new lines and other control characters
-# and jq doesn't like that
-
-a=gets
-
-CONTROL_CHARACTERS = ("\x00".."\x1f").to_a.join("|")
-REGEX= /#{CONTROL_CHARACTERS}/
-
-lines = []
-
-while a do
-  lines << a.gsub(REGEX, "")
-
-  a=gets
-end
-
-puts lines.join(" ")
-EOF
-)
-
-echo $result | ruby -e $ruby_code | jq $selector 2> /dev/null || (echo $result && echo 'failed')
+echo $result | flow-jira-cleanup-response | jq $selector 2> /dev/null || (echo $result && echo 'failed')
